Enabled wowinterface for addon matching
Phanx/wow-addon-updater pull request #11
Opened 2018-04-10 14:31 UTC by jukx

Made wowinterface matching work with both the search overview and redirection to addon page. Before nothing worked.

2018-04-15 03:19 UTC, Phanx requested changes
Needs indentation cleanup throughout; use tabs, not spaces, and make sure levels are consistent (e.g. line 237 should be indented the same as 236 which is +1 indent from 233, but is currently indented less than both).

2018-04-15 03:19 UTC, Phanx commented on sites.lua
> +    cleanedHtml = cleanHTML(html)
This should be a local variable, not global.

2018-04-15 03:19 UTC, Phanx commented on sites.lua
> +                date = tonumber(date),
No need for `tonumber` here; the value returned by `getTimestamp` is already a number.

2018-04-15 03:19 UTC, Phanx commented on sites.lua
> +		if am == "PM" then hh = tonumber(hh) + 12 end
Let's safety-check this and make sure the `match` from the previous line actually resulted in values before we try to manipulate the values.

2018-04-15 03:19 UTC, Phanx commented on sites.lua
> +                site = site,
Should be `site = "wowinterface",` after f2823de

2018-04-15 03:19 UTC, Phanx commented on sites.lua
> +                    date = tonumber(date),
Same as above; no need for `tonumber`.

2018-04-15 10:22 UTC, jukx commented
Issues should be fixed.

2018-04-15 10:26 UTC, jukx commented on sites.lua
> +		if am == "PM" then hh = tonumber(hh) + 12 end
now checking hh before modifying it

2018-04-28 12:33 UTC, Phanx approved these changes

2018-04-28 12:33 UTC, merged